name: Build EXE and APK

on:
  push:
    branches: [ main, beta, alpha, nightly, pre ]
  pull_request:
    branches: [ main, beta, alpha, nightly, pre ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.5
          
      - name: Grant Execute Permission
        run: git update-index --chmod=+x gradlew
        
      - name: Build Android APK
        run: ./gradlew :androidApp:assembleDebug --stacktrace
        
      - name: Build Windows EXE
        run: ./gradlew :desktopApp:packageExe --stacktrace
        
      - name: Upload Universal APK
        uses: actions/upload-artifact@v4
        with:
          name: omlet-arcade-universal-apk
          path: androidApp/build/outputs/apk/debug/*universal*.apk
          
      - name: Upload arm64-v8a APK
        uses: actions/upload-artifact@v4
        with:
          name: omlet-arcade-arm64-v8a-apk
          path: androidApp/build/outputs/apk/debug/*arm64-v8a*.apk
          
      - name: Upload armeabi-v7a APK
        uses: actions/upload-artifact@v4
        with:
          name: omlet-arcade-armeabi-v7a-apk
          path: androidApp/build/outputs/apk/debug/*armeabi-v7a*.apk

      - name: Upload x86_64 APK
        uses: actions/upload-artifact@v4
        with:
          name: omlet-arcade-x86_64-apk
          path: androidApp/build/outputs/apk/debug/*x86_64*.apk
          
      - name: Upload Windows EXE
        uses: actions/upload-artifact@v4
        with:
          name: omlet-arcade-windows-exe
          path: desktopApp/build/compose/binaries/main/exe/*.exe

